// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/pairing/v1/pairing.proto

package pairingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score            int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	AvoidedOpponents []string               `protobuf:"bytes,3,rep,name=avoided_opponents,json=avoidedOpponents,proto3" json:"avoided_opponents,omitempty"`
	WhiteCount       int32                  `protobuf:"varint,4,opt,name=white_count,json=whiteCount,proto3" json:"white_count,omitempty"`
	BlackCount       int32                  `protobuf:"varint,5,opt,name=black_count,json=blackCount,proto3" json:"black_count,omitempty"`
	LastColor        string                 `protobuf:"bytes,6,opt,name=last_color,json=lastColor,proto3" json:"last_color,omitempty"`
	ReceivedBye      bool                   `protobuf:"varint,7,opt,name=received_bye,json=receivedBye,proto3" json:"received_bye,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_pairing_v1_pairing_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetAvoidedOpponents() []string {
	if x != nil {
		return x.AvoidedOpponents
	}
	return nil
}

func (x *Player) GetWhiteCount() int32 {
	if x != nil {
		return x.WhiteCount
	}
	return 0
}

func (x *Player) GetBlackCount() int32 {
	if x != nil {
		return x.BlackCount
	}
	return 0
}

func (x *Player) GetLastColor() string {
	if x != nil {
		return x.LastColor
	}
	return ""
}

func (x *Player) GetReceivedBye() bool {
	if x != nil {
		return x.ReceivedBye
	}
	return false
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WhitePlayerId string                 `protobuf:"bytes,2,opt,name=white_player_id,json=whitePlayerId,proto3" json:"white_player_id,omitempty"`
	BlackPlayerId string                 `protobuf:"bytes,3,opt,name=black_player_id,json=blackPlayerId,proto3" json:"black_player_id,omitempty"`
	BoardNumber   int32                  `protobuf:"varint,4,opt,name=board_number,json=boardNumber,proto3" json:"board_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_pairing_v1_pairing_proto_rawDescGZIP(), []int{1}
}

func (x *Match) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Match) GetWhitePlayerId() string {
	if x != nil {
		return x.WhitePlayerId
	}
	return ""
}

func (x *Match) GetBlackPlayerId() string {
	if x != nil {
		return x.BlackPlayerId
	}
	return ""
}

func (x *Match) GetBoardNumber() int32 {
	if x != nil {
		return x.BoardNumber
	}
	return 0
}

type PairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TournamentId  string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_pairing_v1_pairing_proto_rawDescGZIP(), []int{2}
}

func (x *PairingRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *PairingRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PairingRequest) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type PairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Matches       []*Match               `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ByePlayerId   string                 `protobuf:"bytes,4,opt,name=bye_player_id,json=byePlayerId,proto3" json:"bye_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingResponse) Reset() {
	*x = PairingResponse{}
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingResponse) ProtoMessage() {}

func (x *PairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pairing_v1_pairing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingResponse.ProtoReflect.Descriptor instead.
func (*PairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_pairing_v1_pairing_proto_rawDescGZIP(), []int{3}
}

func (x *PairingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PairingResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *PairingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PairingResponse) GetByePlayerId() string {
	if x != nil {
		return x.ByePlayerId
	}
	return ""
}

var File_proto_pairing_v1_pairing_proto protoreflect.FileDescriptor

const file_proto_pairing_v1_pairing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/pairing/v1/pairing.proto\x12\n" +
	"pairing.v1\"\xec\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12+\n" +
	"\x11avoided_opponents\x18\x03 \x03(\tR\x10avoidedOpponents\x12\x1f\n" +
	"\vwhite_count\x18\x04 \x01(\x05R\n" +
	"whiteCount\x12\x1f\n" +
	"\vblack_count\x18\x05 \x01(\x05R\n" +
	"blackCount\x12\x1d\n" +
	"\n" +
	"last_color\x18\x06 \x01(\tR\tlastColor\x12!\n" +
	"\freceived_bye\x18\a \x01(\bR\vreceivedBye\"\x95\x01\n" +
	"\x05Match\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12&\n" +
	"\x0fwhite_player_id\x18\x02 \x01(\tR\rwhitePlayerId\x12&\n" +
	"\x0fblack_player_id\x18\x03 \x01(\tR\rblackPlayerId\x12!\n" +
	"\fboard_number\x18\x04 \x01(\x05R\vboardNumber\"y\n" +
	"\x0ePairingRequest\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12,\n" +
	"\aplayers\x18\x03 \x03(\v2\x12.pairing.v1.PlayerR\aplayers\"\xa1\x01\n" +
	"\x0fPairingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\amatches\x18\x02 \x03(\v2\x11.pairing.v1.MatchR\amatches\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\"\n" +
	"\rbye_player_id\x18\x04 \x01(\tR\vbyePlayerId2]\n" +
	"\x0ePairingService\x12K\n" +
	"\x10GeneratePairings\x12\x1a.pairing.v1.PairingRequest\x1a\x1b.pairing.v1.PairingResponseB2Z0tournament-engine/pkg/proto/pairing/v1;pairingv1b\x06proto3"

var (
	file_proto_pairing_v1_pairing_proto_rawDescOnce sync.Once
	file_proto_pairing_v1_pairing_proto_rawDescData []byte
)

func file_proto_pairing_v1_pairing_proto_rawDescGZIP() []byte {
	file_proto_pairing_v1_pairing_proto_rawDescOnce.Do(func() {
		file_proto_pairing_v1_pairing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pairing_v1_pairing_proto_rawDesc), len(file_proto_pairing_v1_pairing_proto_rawDesc)))
	})
	return file_proto_pairing_v1_pairing_proto_rawDescData
}

var file_proto_pairing_v1_pairing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pairing_v1_pairing_proto_goTypes = []any{
	(*Player)(nil),          // 0: pairing.v1.Player
	(*Match)(nil),           // 1: pairing.v1.Match
	(*PairingRequest)(nil),  // 2: pairing.v1.PairingRequest
	(*PairingResponse)(nil), // 3: pairing.v1.PairingResponse
}
var file_proto_pairing_v1_pairing_proto_depIdxs = []int32{
	0, // 0: pairing.v1.PairingRequest.players:type_name -> pairing.v1.Player
	1, // 1: pairing.v1.PairingResponse.matches:type_name -> pairing.v1.Match
	2, // 2: pairing.v1.PairingService.GeneratePairings:input_type -> pairing.v1.PairingRequest
	3, // 3: pairing.v1.PairingService.GeneratePairings:output_type -> pairing.v1.PairingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pairing_v1_pairing_proto_init() }
func file_proto_pairing_v1_pairing_proto_init() {
	if File_proto_pairing_v1_pairing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pairing_v1_pairing_proto_rawDesc), len(file_proto_pairing_v1_pairing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pairing_v1_pairing_proto_goTypes,
		DependencyIndexes: file_proto_pairing_v1_pairing_proto_depIdxs,
		MessageInfos:      file_proto_pairing_v1_pairing_proto_msgTypes,
	}.Build()
	File_proto_pairing_v1_pairing_proto = out.File
	file_proto_pairing_v1_pairing_proto_goTypes = nil
	file_proto_pairing_v1_pairing_proto_depIdxs = nil
}
