// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/pairing/v1/pairing.proto

package pairingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PairingService_GeneratePairings_FullMethodName = "/pairing.v1.PairingService/GeneratePairings"
)

// PairingServiceClient is the client API for PairingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PairingServiceClient interface {
	GeneratePairings(ctx context.Context, in *PairingRequest, opts ...grpc.CallOption) (*PairingResponse, error)
}

type pairingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPairingServiceClient(cc grpc.ClientConnInterface) PairingServiceClient {
	return &pairingServiceClient{cc}
}

func (c *pairingServiceClient) GeneratePairings(ctx context.Context, in *PairingRequest, opts ...grpc.CallOption) (*PairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairingResponse)
	err := c.cc.Invoke(ctx, PairingService_GeneratePairings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PairingServiceServer is the server API for PairingService service.
// All implementations must embed UnimplementedPairingServiceServer
// for forward compatibility.
type PairingServiceServer interface {
	GeneratePairings(context.Context, *PairingRequest) (*PairingResponse, error)
	mustEmbedUnimplementedPairingServiceServer()
}

// UnimplementedPairingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPairingServiceServer struct{}

func (UnimplementedPairingServiceServer) GeneratePairings(context.Context, *PairingRequest) (*PairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePairings not implemented")
}
func (UnimplementedPairingServiceServer) mustEmbedUnimplementedPairingServiceServer() {}
func (UnimplementedPairingServiceServer) testEmbeddedByValue()                        {}

// UnsafePairingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PairingServiceServer will
// result in compilation errors.
type UnsafePairingServiceServer interface {
	mustEmbedUnimplementedPairingServiceServer()
}

func RegisterPairingServiceServer(s grpc.ServiceRegistrar, srv PairingServiceServer) {
	// If the following call panics, it indicates UnimplementedPairingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PairingService_ServiceDesc, srv)
}

func _PairingService_GeneratePairings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).GeneratePairings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PairingService_GeneratePairings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).GeneratePairings(ctx, req.(*PairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PairingService_ServiceDesc is the grpc.ServiceDesc for PairingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PairingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pairing.v1.PairingService",
	HandlerType: (*PairingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePairings",
			Handler:    _PairingService_GeneratePairings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pairing/v1/pairing.proto",
}
